Description: Container registry
Parameters:
  ContainerRegistryName:
    Description: Container registry name
    Type: String
  IAMUsername:
    Description: IAM Username to have access
    Type: String
Resources:
  ContainerRegistry:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ContainerRegistryName
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:user/${IAMUsername}
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
