---
AWSTemplateFormatVersion: 2010-09-09

Description: Aurora serverless cluster

Parameters:
  DatabaseName:
    Type: String
  EngineVersion:
    Type: String
    Default: '5.6'
  MasterUsername:
    Type: String
    Default: root
  MasterUserPassword:
    Type: String
    NoEcho: true
  VpcId:
    Type: AWS::EC2::VPC::Id
  VpcSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
  BastionImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn-ami-hvm-x86_64-ebs
  BastionKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 key used to connect to the bastion host
  BastionInstanceRole:
    Type: String
    Description: Role to be assigned for the bastion host to run migrations

Resources:
  SecretKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: 2012-10-17
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Join
                - ''
                - - 'arn:aws:iam::'
                  - !Ref 'AWS::AccountId'
                  - ':root'
            Action: 'kms:*'
            Resource: '*'
  Cluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora
      EngineMode: serverless
      EngineVersion: !Ref EngineVersion
      DatabaseName: !Ref DatabaseName
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      DBClusterIdentifier: !Ref AWS::StackName
      BackupRetentionPeriod: 28
      DeletionProtection: false
      StorageEncrypted: true
      KmsKeyId: !Ref SecretKey
      VpcSecurityGroupIds:
        - !Ref VpcSecurityGroupId

  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: !Sub 'Bastion for ${AWS::StackName}'
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          FromPort: -1
          ToPort: -1
          IpProtocol: '-1'
        - DestinationSecurityGroupId: !Ref VpcSecurityGroupId
          IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
      SecurityGroupIngress: []
      VpcId: !Ref VpcId
  
  BastionInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles:
        - !Ref BastionInstanceRole

  Bastion:
    Type: AWS::EC2::Instance
    Properties:
      DisableApiTermination: true
      ImageId: !Ref BastionImageId
      InstanceType: t3.nano
      KeyName: !Ref BastionKeyName
      IamInstanceProfile: !Ref BastionInstanceProfile
      Monitoring: false
      SecurityGroupIds:
        - !Ref VpcSecurityGroupId
        - !Ref BastionSecurityGroup
      UserData: !Base64 'yum install mysql --assumeyes'

Outputs:
  Host:
    Value: !GetAtt Cluster.Endpoint.Address
    Export:
      Name: !Sub '${AWS::StackName}Host'
  Name:
    Value: !Ref DatabaseName
    Export:
      Name: !Sub '${AWS::StackName}Name'
  BastionHost:
    Value: !GetAtt Bastion.PublicDnsName
    Export:
      Name: !Sub '${AWS::StackName}BastionHost'
  BastionIp:
    Value: !GetAtt Bastion.PublicIp
    Export:
      Name: !Sub '${AWS::StackName}BastionIp'
  BastionSecurityGroupId:
    Value: !GetAtt BastionSecurityGroup.GroupId
    Export:
      Name: !Sub '${AWS::StackName}BastionSecurityGroupId'