AWSTemplateFormatVersion: 2010-09-09
Description: RDS Storage Test DB
Parameters:
  DBInstanceClass:
    Type: String
  DBName:
    Type: String
  AllocatedStorage:
    Type: String
    Default: 5
  Engine:
    Type: String
    Default: Postgres
  Username:
    Type: String
  Password:
    Type: String
  VpcId:
    Type: String
Resources:
  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join
        - '.'
        - - !Ref Engine
          - !Ref DBInstanceClass
          - !Ref DBName
      GroupDescription: Database custom security group
      VpcId: !Ref VpcId
      Tags:
      - Key: CostCenter
        Value: Rapidobuild
      - Key: Purpose
        Value: Test environment
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBName
      AllocatedStorage: !Ref AllocatedStorage
      DBInstanceClass: !Ref DBInstanceClass
      MasterUsername: !Ref Username
      MasterUserPassword: !Ref Password
      Engine: !Ref Engine
      DeletionProtection: false
      PubliclyAccessible: false
      BackupRetentionPeriod: 1
      CopyTagsToSnapshot: true
      DeleteAutomatedBackups: false
      EngineVersion: 10.6
      VPCSecurityGroups:
        - !Ref DatabaseSecurityGroup
      Tags:
      - Key: CostCenter
        Value: Rapidobuild
      - Key: Purpose
        Value: Test environment
    DeletionPolicy: Delete
Outputs:
  DatabaseSecurityGroupId:
    Value: !Ref DatabaseSecurityGroup
    Export:
      Name: "DatabaseSecurityGroup::Id"
  JDBCConnectionString:
    Description: JDBC connection string for the database
    Value: !Join ['', ['jdbc:postgres://', !GetAtt [Database, Endpoint.Address], ':', !GetAtt [
          Database, Endpoint.Port], '/',!Ref DBName]]
