AWSTemplateFormatVersion: 2010-09-09
Description: RDS Storage Encrypted Prod DB
Parameters:
  DBInstanceClass:
    Type: String
  DBName:
    Type: String
  AllocatedStorage:
    Type: String
    Default: 5
  Engine:
    Type: String
    Default: mysql
  Username:
    Type: String
  Password:
    Type: String
  VpcId:
    Type: String
Resources:
  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join
        - '.'
        - - !Ref Engine
          - !Ref DBInstanceClass
          - !Ref DBName
      GroupDescription: Database custom security group
      VpcId: !Ref VpcId
      Tags:
      - Key: CostCenter
        Value: Rapidobuild
      - Key: Purpose
        Value: Test environment
  SecretKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: 2012-10-17
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Join
                - ''
                - - 'arn:aws:iam::'
                  - !Ref 'AWS::AccountId'
                  - ':root'
            Action: 'kms:*'
            Resource: '*'
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBName
      AllocatedStorage: !Ref AllocatedStorage
      DBInstanceClass: !Ref DBInstanceClass
      StorageEncrypted: true
      KmsKeyId: !Ref SecretKey
      MasterUsername: !Ref Username
      MasterUserPassword: !Ref Password
      Engine: !Ref Engine
      DeletionProtection: true
      PubliclyAccessible: false
      BackupRetentionPeriod: 7
      CopyTagsToSnapshot: true
      DeleteAutomatedBackups: false
      EngineVersion: 10.6
      VPCSecurityGroups:
        - !Ref DatabaseSecurityGroup
      Tags:
      - Key: CostCenter
        Value: Rapidobuild
      - Key: Purpose
        Value: Production encrypted
    DeletionPolicy: Snapshot
Outputs:
  DatabaseSecurityGroupId:
    Value: !Ref DatabaseSecurityGroup
    Export:
      Name: "DatabaseSecurityGroup::Id"
  JDBCConnectionString:
    Description: JDBC connection string for the database
    Value: !Join ['', ['jdbc:postgres://', !GetAtt [Database, Endpoint.Address], ':', !GetAtt [
          Database, Endpoint.Port], '/',!Ref DBName]]
