AWSTemplateFormatVersion: 2010-09-09
Description: RDS Storage Test DB
Parameters:
  DBInstanceClass:
    Type: String
  DBName:
    Type: String
  AllocatedStorage:
    Type: String
    Default: 5
  Engine:
    Type: String
    Default: mysql
  Username:
    Type: String
  Password:
    Type: String
  Port:
    Type: String
    Default: 3306
  VpcId:
    Type: 'AWS::EC2::VPC::Id'
    Description: VPC IDs
  PrivateSubnets:
    Type: CommaDelimitedList
    Description: Subnet IDs
  EngineVersion:
    Type: String
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: dev
    AllowedValues: [prod, dev, stage]
    ConstraintDescription: Must specify prod, dev, or stage.
Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DBSubnetGroup
      DBSubnetGroupName: !Join
        - '-'
        - - !Ref DBName
          - !Ref EnvironmentName
          - "subnet-group"
      SubnetIds: !Ref PrivateSubnets
      Tags:
      - Key: CostCenter
        Value: Rapidobuild
      - Key: Environment
        Value: !Ref EnvironmentName
  LocalAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Enable tcp access from OnPremise network
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref Port
          ToPort: !Ref Port
          CidrIp: 10.0.0.0/8
  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join
        - '.'
        - - !Ref Engine
          - !Ref DBInstanceClass
          - !Ref DBName
      GroupDescription: Database custom security group
      VpcId: !Ref VpcId
      Tags:
      - Key: CostCenter
        Value: Rapidobuild
      - Key: Environment
        Value: !Ref EnvironmentName
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBName
      AllocatedStorage: !Ref AllocatedStorage
      DBInstanceClass: !Ref DBInstanceClass
      MasterUsername: !Ref Username
      MasterUserPassword: !Ref Password
      DBSubnetGroupName: !Ref DBSubnetGroup
      StorageEncrypted: true
      Engine: !Ref Engine
      Port: !Ref Port
      DeletionProtection: false
      PubliclyAccessible: false
      BackupRetentionPeriod: 1
      CopyTagsToSnapshot: true
      DeleteAutomatedBackups: false
      EngineVersion: !Ref EngineVersion
      VPCSecurityGroups:
        - !Ref DatabaseSecurityGroup
        - !Ref LocalAccessSecurityGroup
      Tags:
      - Key: CostCenter
        Value: Rapidobuild
      - Key: Environment
        Value: !Ref EnvironmentName
    DeletionPolicy: Delete
Outputs:
  DatabaseSecurityGroupId:
    Value: !Ref DatabaseSecurityGroup
  JDBCConnectionString:
    Description: JDBC connection string for the database
    Value: !Join ['', ['jdbc:', !Ref Engine, '://', !GetAtt [Database, Endpoint.Address], ':', !GetAtt [
          Database, Endpoint.Port], '/',!Ref DBName]]
