Description: Bucket for storing secrets
Parameters:
  SecretsBucketName:
    Description: BucketName to store secrets
    Type: String
Resources:
  AssetsS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      BucketName: !Ref SecretsBucketName
      Tags:
      - Key: CostCenter
        Value: Rapidobuild
      - Key: Purpose
        Value: Secrets
    DeletionPolicy: Retain


